services:
  mysql:
    image: mysql:latest
    container_name: my_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ript
      MYSQL_DATABASE: btl
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: